
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - jq/install
      - run: sudo apt-get update && sudo apt-get install curl
      - run:
          name: Authenticate With DSV Vault 
          command: | 
            DSV_URL = 'https://grregg.secretsvaultcloud.com/v1/token'
            -echo "$DSV_URL"
            export AUTH_REQUEST=$(curl --request POST --header 'Content-Type: application/x-www-form-urlencoded' --data '{ \"grant_type\": \"client_credentials\", \"client_id\": \"'$client_id'\", \"client_secret\": \"'$client_secret'\"}' https://grregg.secretsvaultcloud.com/v1/token) 
            -echo "Authentication successful, grabbing Bearer Token"
            -export BEARER_TOKEN=$(echo $AUTH_REQUEST | jq -r '.accessToken')
